name: Sha1 Generator

on: 
  release:
    types: [created]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: MCJack123/ghaction-Generate-Release-Hashes@v4
      with:
        hash-type: sha1
        file-name: hashes.txt
      
    - uses: actions/upload-artifact@v2
      with:
        name: Asset Hashes
        path: hashes.txt
