name: Resourcepack Zipper

on:
  push:
    branches:
      - main  # Adjust this branch name if needed
    paths:
      - assets/**
      - pack.mcmeta
      - pack.png
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # A non-shallow repository clone is required

    - name: Run PackSquash
      uses: ComunidadAylas/PackSquash-action@v4
      with:
        packsquash_version: latest # Uses the latest PackSquash release supported by the action
        options: |
          pack_directory = '.'
          output_file_path = '/tmp/Deathmatch Resources.zip'
          validate_pack_metadata_file = false
          
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.RESOURCE_ZIPPER }}
        tag_name: release-${{ github.sha }}
        name: Release ${{ github.sha }}
        files: |
          /tmp/Deathmatch Resources.zip
          
